#!/bin/bash -e

cd $(dirname $0)/..

stack build
stack exec -- random-lisp > example/output.js
uglifyjs -c -m --mangle-props --toplevel < example/output.js > example/output.min.js
wc -c example/output.min.js
