name:                random-lisp
version:             0.1.0.0
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - hspec
  - hspec-megaparsec
  - pretty-show
  - containers
  - mtl
  - transformers

executables:
  random-lisp:
    source-dirs:      src
    main:             Main.hs
